name = "seportal-pages"
compatibility_date = "2024-11-01"
pages_build_output_dir = "./build/client"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "seportal-db"
database_id = "77da92f7-e197-4d6e-bef1-1567ff404afa"

# KV namespace binding
[[kv_namespaces]]
binding = "KV"
id = "66a4c597ef8749b99263134606222f5a"

# R2 bucket binding
[[r2_buckets]]
binding = "R2"
bucket_name = "seportal-storage"

# Durable Objects bindings (will bind to Worker)
[[durable_objects.bindings]]
name = "COLLAB"
class_name = "CollabRoom"
script_name = "seportal-durable"

# Service binding to API Worker
[[services]]
binding = "API_WORKER"
service = "seportal-api"

# Service binding to Cron Worker (if needed for manual triggers)
[[services]]
binding = "CRON_WORKER"
service = "seportal-cron"
